mdolab/pyoptsparse

- postprocessing/OptView.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pySNOPT/pySNOPT.py
Fixes to major iteration counting (still not perfect)
Seemed to fix minor iteration counting bug; need to clean up still
Fixed for py3
Updates to OptView for major iteration; works for pyoptsparse and OpenMDAO
Fixed OptView so multiple outputs can be saved to Tec file correctly
Fixed whitespace in objective
> Migrating existing Bitbucket pull request to Github

- pyoptsparse/pySLSQP/pySLSQP.py
Changed dummyConstraint to True in SLSQP. This will allow setting up unconstraint problems.
> Changed dummyConstraint to True in SLSQP.

- doc/postprocessing.rst
- postprocessing/SNOPT_parse.py
Addresses #22 
File is taken directly from http://mdolab.engin.umich.edu/content/snopt-print-file-parsing
>  added file for parsing SNOPT printout files

- postprocessing/OptView_dash.py
This OptView was written using the Dash framework. This still doesn't carry all the features of tcl based OptView but covers the main ones.
User has to pip install dash and run the python script
python OptView_dash.py <history file>
> Added new Opt View based on Dash framework

- postprocessing/assets/base-styles.css
- postprocessing/assets/custom-styles.css
Added style sheets for better color design
> Added css files for better layout

- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pyParOpt/ParOpt.py
- pyoptsparse/pySNOPT/pySNOPT.py
- test/test_hs071.py
I fixed the code that post-processes the multipliers after the optimization.
I added a test to test_hs071.py to test the multiplier values.
> Fix for multiplier post-processing code

- README.md
- doc/api/optimization.rst
- doc/optimizers.rst
- doc/optimizers/paropt.rst
- doc/optimizers/pyalpso.rst
- doc/optimizers/pyconmin.rst
- doc/optimizers/pyfsqp.rst
- doc/optimizers/pyipopt.rst
- doc/optimizers/pynlpqlp.rst
- doc/optimizers/pynsga2.rst
- doc/optimizers/pyparopt.rst
- doc/optimizers/pyslsqp.rst
- doc/optimizers/pysnopt.rst
- pyoptsparse/pyNLPQLP/pyNLPQLP.py
- release_notes.md
- test/test_hs015.py
- test/test_hs071.py
A number of things were changed in preparation for the initial release.
- Updated README and added release notes
- Updated docs to explain which versions of optimizers are tested, and added some installation instructions.
- Updated tests
> Minor fixes in preparation for release v1.0

- pyoptsparse/pyOpt_optimization.py
- test/test_hs015.py
Bug fix for printing of optimization problem/solution.
Need to add a test that prints the optimization problem so that this doesn't happen again.
> Fixed the printing of the lagrange multipliers.

- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_optimizer.py
- test/test_snopt_bugfix.py
Recent Lagrange multiplier feature broke unconstrained optimization.  Also made a further fix on the lagrange multiplier printing. 
Added a test that shows that we no longer get a Type Error exception for an unconstrained problem.
> Fixed a TypeError for unconstrained optimization.

- doc/optimizers/pyipopt.rst
- pyoptsparse/pyIPOPT/src/callback.c
- pyoptsparse/pyIPOPT/src/hook.h
- pyoptsparse/pyIPOPT/src/pyipoptcoremodule.c
Minimum change fix to the pyIPOPT wrapper to allow it to compile using Python 3
Pulled the latest pyIPOPT Python wrapper source files from https://github.com/xuy/pyipopt
- Bugfix
- [ x] I have run unit and regression tests which pass locally with my changes
- [ x] I have added necessary documentation
> py3 segfault fix closes #13

- .travis.yml
Fix bashrc issue in travis.yml
> Add coveralls

- pyoptsparse/pyALPSO/alpso.py
- pyoptsparse/pyALPSO/alpso_ext.py
- pyoptsparse/pyCONMIN/pyCONMIN.py
- pyoptsparse/pyOpt_constraint.py
- pyoptsparse/pyOpt_error.py
- pyoptsparse/pyOpt_history.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pySNOPT/pySNOPT.py
- test/test_hs015.py
- test/test_nsga2_multi_objective.py
Addresses #74.
The pyOpt_History object has always lacked a full set of API for accessing the history file. As a result, everyone wrote their own scripts to parse through the history file, which causes code duplication. Furthermore, as the history file evolves, certain backwards-incompatible changes have been introduced which will break these codes.
Here we introduce some API for postprocessing an optimization, providing a way to access the data within the history file. In the future, it is hoped that these API will perform version checking against what is stored in pyOptSparse, to provide a stable API for future changes. …
> Overhauled history object API

- README.md
- doc/install.rst
> Updated installation docs

- .coveragerc
- .travis.yml
I updated travis and coveralls settings, to omit certain files when calculating the code coverage.
> Updated coveralls setting

- pyoptsparse/__init__.py
From #96 we noticed that ParOpt was not imported correctly in the init file. This PR addresses that issue, although we haven't fully gotten to the bottom of why the paraboloid example doesn't run in some cases.
> Update import of ParOpt

- .flake8
- pyoptsparse/pyALPSO/alpso.py
- pyoptsparse/pyALPSO/alpso_ext.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyParOpt/ParOpt.py
This PR fixes some of the issues from #103.
- formatting and flake8
- updates to ParOpt wrapper
- removed `norm_type` since it's set in `_set_paropt_options`
- removed duplicate `_set_paropt_options` call
- added `opt.setAbsOptimalityTol(tr_opt_abs_tol)` back
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
> Format fix

- .github/workflows/main.yml
- setup.py
Do not allow installation via pip or setuptools without required dependencies installed
uninstalled sqlitedict
installed per docs
sqlitedict installed automatically
> require sqlitedict for minimal installation closes 105

- pyoptsparse/pyOpt_optimization.py
Updated the docstring for setDVs to reflect the changes made in #109 
> updated setDVs docstring

- doc/conf.py
- Set math to be rendered as mathjax. This offers the possibility of copying expressions over to latex.
- Update the year
> Set math rendering to mathjax and updating date

- doc/guide.rst
- doc/install.rst
Fixing few typos and addressing build warnings.
Verify the build output on readthedocs.com
> Fixing few typos and addressing build warnings.

- .github/PULL_REQUEST_TEMPLATE.md
- doc/contribute.rst
- doc/index.rst
I added a short guide, adapted from the one for OpenAeroStruct, on how to contribute to the code.
> Added guide on how to contribute

- pyoptsparse/pyPSQP/pyPSQP.py
Fixes #146 by adding some negative informs and redirecting unspecified negative values to `-10`.
> added PSQP negative informs

- doc/install.rst
As per title, I edited the installation .rst file. It now includes a link to the bash script that OpenMDAO developers made to facilitate the installation of IPOPT.
> Added link to OpenMDAO / build_pyoptsparse

- requirements.txt
- setup.py
This is a re-submission of #159 but without any modifications to `requirements.txt`. I simply removed the patch versions from dependencies.
- Maintenance
> Removed patch version from dependencies

- doc/install.rst
I added a note to recommend gcc/gfortran for the appropriate compilers.
> Added note on C/Fortran compilers in docs

- pyoptsparse/pyCONMIN/pyCONMIN.py
- pyoptsparse/pyNLPQLP/pyNLPQLP.py
- pyoptsparse/pyPSQP/pyPSQP.py
- test/test_rosenbrock.py
As pointed out in #157, few optimizers in pyOptSparse do not natively support an unconstrained optimization problem formulation.
We fix this issue using `dummyConstraint` option from the `Optimization()` class, indeed providing a dummy constraint to the algorithm to complete the input set.
As this kind of optimization problem was untested, the option was not turned on for PSQP, CONMIN, and NLPQLP.
Now the feature is enabled, supporting unconstrained optimization problems throughout pyOptSparse. 
Moreover, I added a new test based on the Rosenbrock function to verify that all our optimizers support unconstrained problems.
Closes #157 and partially addresses #145.
Run the entire test suite or just the newly added `test_rosenbrock.py`
> Bugfix and testing for unconstrained optimization

- .travis.yml
- pyoptsparse/pyOpt_optimization.py
- setup.py
- test/test_large_sparse.py
- test/test_snopt_bugfix.py
- test/test_snopt_user_termination.py
This PR removes the (fairly undocumented) feature of tuple-based indexing of the sensitivity dictionary (similar to OpenMDAO), since it seemed like very few people were actually using it, and I don't really see a lot of benefit in supporting both.
The tests that used this approach were also updated.
- Breaking change (non-backwards-compatible fix or feature)
> Remove flat sensitivity dict

- pyoptsparse/pyOpt_utils.py
Addresses #170.
No code changes.
> Removed unnecessary comments for scipy

- .travis.yml
- doc/guide.rst
- examples/tp037.py
This PR updates the documentation and the associated example to explain both ways for instantiating the optimizer object. Closes #169.
No code has changed.
> Updated docs to explain both ways of creating optimizer

- README.md
- doc/citation.rst
- doc/conf.py
- doc/contribute.rst
- doc/index.rst
Added citation information for the JOSS paper.
N/A
> Added citation information

- doc/optimizers/pyparopt.rst
This is a very small update to the documentation to point to the correct repository and the installation instruction for the supported optimiser ParOpt.
Hopefully this will help someone else when they try to find the install instructions.
I've not tried rebuilding the docs with those changes, so that needs to get done.
> Update link to ParOpt repository and documentation

- pyoptsparse/pyOpt_variable.py
This PR adds the missing `offset` attribute to the `Variable` class if it is an integer variable. Related to #163 but the point is a bit moot since pyOptSparse does not currently have any optimizers that support discrete variables.
Existing tests pass. No new tests can be added since this feature is supporting a non-existant capability.
> Added missing offset attribute to integer dvs

- pyoptsparse/pyALPSO/pyALPSO.py
- pyoptsparse/pyCONMIN/pyCONMIN.py
- pyoptsparse/pyIPOPT/pyIPOPT.py
- pyoptsparse/pyNLPQLP/pyNLPQLP.py
- pyoptsparse/pyNOMAD/pyNOMAD.py
- pyoptsparse/pyNSGA2/pyNSGA2.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyPSQP/pyPSQP.py
- pyoptsparse/pyParOpt/ParOpt.py
- pyoptsparse/pySLSQP/pySLSQP.py
- pyoptsparse/pySNOPT/pySNOPT.py
- test/test_snopt_bugfix.py
- test/test_snopt_user_termination.py
The way we called finalize before was pretty messy. Instead, I did the following:
- added a field called `finalized` which stores whether everything has already been finalized
- added a function called `finalize()` which will call both DV and constraint finalize functions, but only if it's not been finalized yet
- set the `finalized` flag to false if a function modifies the DVs or constraints
- made the `finalizeDesignVariables` and `finalizeConstraints` functions private in the hopes that user will not call them directly
No change since this is just a refactor
> Refactored finalize functions

- .github/build_real.sh
- setup.py
This adds a minimum testflo version that includes the `--disallow_skipped` flag.
> Specified testflo version

- pyoptsparse/pyOpt_gradient.py
This fixes the complex casting warnings when using FD. There is no reason for `fconBase` to be complex because it is only used for finite difference, not complex-step.
> Fixed complex casting in FD

- doc/advancedFeatures.rst
- doc/postprocessing.rst
- pyoptsparse/__init__.py
I added a short bit of documentation to describe how to set up the history file set up and how to use the `timeLimit` option.
Please check it out and add more details if necessary!
> Updated `Advanced Features` section

- doc/advancedFeatures.rst
Fix small typo in docs from last commit.
> Fix typo in advancedFeatures.rst

- .github/azure-pipelines.yaml
- .github/build_real.sh
- .github/test_real.sh
This PR adds codecov for coverage reporting. This will probably take a few tries to get everything sorted so please don't merge it just yet.
> Add coverage report

- .coveragerc
- .github/build_real.sh
- README.md
- codecov.yml
This PR modifies some coverage-related files, and tests that everything is working as expected.
> Test coverage

- pyoptsparse/pyOpt_optimization.py
Closes #264 by allowing objFun to be pickled if possible. We use a blanket Exception to avoid issues with the tests and MACH.
> Allow objFun pickling if possible 

- pyoptsparse/pyIPOPT/setup.py
Closes #262.
Let's see if this builds fine. If IPOPT tests all pass then I think we are good to go.
> Remove other linked libraries when building `ipoptcore`

- examples/hs015.py
- pyoptsparse/pyOpt_constraint.py
- pyoptsparse/pyOpt_history.py
- pyoptsparse/pyOpt_objective.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pyOpt_solution.py
- pyoptsparse/pyOpt_utils.py
- pyoptsparse/pyOpt_variable.py
- pyoptsparse/pySNOPT/pySNOPT.py
I used `flynt` to convert old-style strings to f-strings. In addition, there were a bunch of manual fixes, so it would be helpful of reviewers are careful in reviewing this to make sure I didn't break anything.
N/A
> Convert to f-strings

- doc/install.rst
Added note in documentation on potential (and unsupported) macOS/Windows builds.
> Added note in documentation on macOS/Windows builds

- pyoptsparse/pyOpt_error.py
- tests/test_snopt_bugfix.py
- tests/test_snopt_user_termination.py
Adding a message attribute to PyOptSparse Exceptions which allows for parsing of exceptions.
The motivation behind adding the message attribute is to be able to differentiate between `Error`s during testing. For example, to know whether an error is due to the SNOPT libraries not being available or due to problem option incompatibility.
Raise `Error()` during the evaluation of the problem objective or sensitivities and check that the raised error instance has a `message` attribute.
> Add message attribute to Exceptions

- doc/api/history.rst
- pyoptsparse/pyALPSO/pyALPSO.py
- pyoptsparse/pyCONMIN/pyCONMIN.py
- pyoptsparse/pyIPOPT/pyIPOPT.py
- pyoptsparse/pyNLPQLP/pyNLPQLP.py
- pyoptsparse/pyNSGA2/pyNSGA2.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pyPSQP/pyPSQP.py
- pyoptsparse/pyParOpt/ParOpt.py
- pyoptsparse/pySLSQP/pySLSQP.py
- pyoptsparse/pySNOPT/pySNOPT.py
- tests/test_snopt_bugfix.py
- tests/test_snopt_user_termination.py
- tests/testing_utils.py
This was a popular feature request. Closes #147. The history file will now have `time` embedded in each iteration, which is helpful for plotting values against time instead of just iterations. Unfortunately the implementation is a bit crude since the same boilerplate code is in each optimizer wrapper---see #220. Nevertheless, this works and I've added some tests also.
I also added a basic`tearDown` implementation to clean up some of the generated test files, but this is incomplete.
I added some tests.
> Added iteration timing to history file

- .gitignore
- README.md
- pyoptsparse/pyCONMIN/pyCONMIN.py
- pyoptsparse/pySLSQP/pySLSQP.py
- pyoptsparse/pySNOPT/pySNOPT.py
- tests/test_large_sparse.py
This is a maintenance PR to cleanup some of the warnings that occur when running the tests or runscripts.
In detail:
- deprecated `np.float` has been changed to `float` to be consistent with [numpy 1.20](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations)
- tests do not use `scipy.sparse` do define the Jacobian of the linear constraints anymore
- updated `.gitignore` and branch name in the badges
not urgent but very minor PR, EOW
> Np float remove

- doc/optimizers/ALPSO.rst
- doc/optimizers/CONMIN.rst
- doc/optimizers/IPOPT.rst
- doc/optimizers/NLPQLP.rst
- doc/optimizers/NSGA2.rst
- doc/optimizers/PSQP.rst
- doc/optimizers/SLSQP.rst
- doc/optimizers/SNOPT.rst
Given the changes in the sphinx extension at mdolab/sphinx_mdolab_theme#10, I have updated the paths.
A few days.
Docs should build on RTD.
> Updated YAML location to point from current directory

- pyoptsparse/pyOpt_optimizer.py
In some instances, not only will `snSTOP` be un-serializable, but it will also be not copy-able. Therefore, I switched to using a shallow copy for the options.
This should still be fine because other than this, the options are just strings and numbers. I don't think we ever needed the deep copy.
1-2 days.
None
> Switch to shallow copy for options

- pyoptsparse/pyOpt_optimization.py
Updated docstrings of `addConGroup` to make it clear how users should handle the intercept term in linear constraints.
Closes #296 .
Not urgent, but can be merged within a few days.
> Updated docstrings for linear constraint

- pyoptsparse/__init__.py
- pyoptsparse/pySNOPT/pySNOPT.py
Occasionally, the values in `funcs` could contain additional values that are injected after funcs has been saved to file. This PR makes those values available to the snstop function.
Soon.
None
> Update funcs with values from the cache

- pyoptsparse/__init__.py
- pyoptsparse/pySLSQP/pySLSQP.py
Closes #317
1 day
We do not test NumPy 1.24 in our Docker images, but I checked locally that the tests pass with NumPy 1.24.
> Replaced np.int with int

- pyoptsparse/pyOpt_solution.py
This PR is OpenMDAO-centric, as we print out the optimization solution's string representation by default.
This string-representation does not include information about the exit status of the optimizer.
While we can obtain this from files generated by SNOPT or IPOPT, for something like SLSQP, it is not obvious.
New/novice users are often confused by results of a failed optimization, since they see no indication that the optimization failed.
This PR simply adds the inform value/text to the solution's string representation.  It puts it at the end to make it obvious for the user without them having to scroll up through all of the variable and constraint information.
For example:
```
Optimization Problem -- Optimization using pyOpt_sparse …
```
> Added inform to the string representation of the solution.

- examples/hs071_zero_return.py
- pyoptsparse/postprocessing/OptView.py
- pyoptsparse/postprocessing/OptView_baseclass.py
- pyoptsparse/pyALPSO/pyALPSO.py
- pyoptsparse/pyCONMIN/pyCONMIN.py
- pyoptsparse/pyIPOPT/pyIPOPT.py
- pyoptsparse/pyNSGA2/pyNSGA2.py
- pyoptsparse/pyOpt_MPI.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pyOpt_solution.py
- pyoptsparse/pyOpt_utils.py
- pyoptsparse/pySNOPT/pySNOPT.py
- tests/test_hs015.py
- tests/test_nsga2_multi_objective.py
- tests/test_rosenbrock.py
- tests/test_sphere.py
- tests/test_user_termination.py
This PR is to address the recent black-style fix.
> Black style fix for updated version

- doc/optimizers/SNOPT_options.yaml
- pyoptsparse/pySNOPT/pySNOPT.py
The SNOPT option was not displaying correctly, this has now been fixed.
Whenever.
No tests, doc only changes.
> Adjust SNOPT option formatting

- pyoptsparse/__init__.py
Patch version bump since #404 appears stalled.
1 day.
> Version bump

- pyoptsparse/__init__.py
IMO we should bump the version here to 2.13.1, since #425 is going to require a minor bump likely.
> Version bump 2.13.1

- pyoptsparse/pyALPSO/pyALPSO.py
- pyoptsparse/pyCONMIN/pyCONMIN.py
- pyoptsparse/pyNLPQLP/pyNLPQLP.py
- pyoptsparse/pyNSGA2/pyNSGA2.py
- pyoptsparse/pyOpt_constraint.py
- pyoptsparse/pyOpt_error.py
- pyoptsparse/pyOpt_history.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pyOpt_utils.py
- pyoptsparse/pyOpt_variable.py
- pyoptsparse/pyPSQP/pyPSQP.py
- pyoptsparse/pySNOPT/pySNOPT.py
- tests/test_lincon_error.py
> Cleanup error class

- pyoptsparse/pyOpt_optimizer.py
Follow-up to #441 . This fixed the docstrings to properly appear in the docs (see below) while avoiding a syntax warning for the espace sequence.
No rush
> Fix docstrings

- doc/install.rst
> Add note on installing tkinter for optview
