- pyoptsparse/pyOpt_utils.py
Vectorized the inner loop of pyOpt_utils.scaleColumns for improved performance.
for i in range(mat['shape'][0]):
iStart = mat['csr'][IROWP][i]
iEnd = mat['csr'][IROWP][i+1]
for j in range(iStart, iEnd):
mat['csr'][IDATA][j] *= factor[mat['csr'][ICOLIND][j]]
Becomes 
for i in range(mat['shape'][0]):
iStart = mat['csr'][IROWP][i]
iEnd = mat['csr'][IROWP][i+1]
mat['csr'][IDATA][iStart:iEnd] *= factor[mat['csr'][ICOLIND][iStart:iEnd]]
On a optimal control demonstration problem via OpenMDAO this saved about 25 seconds of a total 70 seconds of execution time.
> scaleColumns refactor

- pyoptsparse/pyCONMIN/pyCONMIN.py
- pyoptsparse/pyNSGA2/pyNSGA2.py
- test/test_hs015.py
- test/test_hs071.py
- test/test_large_sparse.py
- test/test_nsga2_multi_objective.py
- test/test_snopt_bugfix.py
- test/test_tp109.py
1. Fixed a bug in pyCONMIN which caused it not to be able to optimize anything with more than one constraint.
2. Dropped the python-deprecated xrange for range. TODO: for py2/3 compatbiility, this should be change ti range from `six`, but that introduces dependency on six.
3. Converted some of the examples over to unittests with asserts.
> A couple of bug fixes and some tests.

- pyoptsparse/pySNOPT/pySNOPT.py
Addresses #38 by simply returning without evaluation on the final call.
SNOPT was designed to do a final evaluation after terminating the main loop, so that if you needed to do any final clean up or file IO, this could be handled by your program. Since we don't need this functionality, we can remove the unnecessary (and very expensive!) function call. This call is signified by `nState =>2`, more specifically `nState = 2 + INFO/10` on the final call.
SNOPT should now run optimization and exit without the extra function call. For example, with default options the `hs015` case should have the last `callCounter` be 20 instead of 21.
> Fix to skip the final and redundant SNOPT call

- pyoptsparse/pyOpt_optimizer.py
The `conInfo` and `varInfo` dictionaries in the db file uses dictionaries and not OrderedDict, so the key order is inconsistent.  This is problematic if you are looping over the DVs or constraints using the keys of the dicts.
This PR addresses the issue by switching to using OrderedDicts. The keys in `varInfo` and `conInfo` now use the ordering in the `optProb`, which is also used elsewhere to write out the `xuser`, so they should all be consistent.
Key ordering in `varInfo` should always match those in `xuser`. `conInfo` should be consistent across multiple executions of the code.
> changed conInfo and varInfo in db to OrderedDict to preserve key order

- pyoptsparse/pySNOPT/pySNOPT.py
Addresses #48. Two things were happening to the SNOPT_print.out
- The optimization name (which is specified as 8 characters) is often truncated incorrectly, or invalid characters are used as padding
- The section on Objective, RHS, Ranges and Bounds all display invalid characters
These cause problems when using meld/vi/diff since the encoding messes it up. This is fixed by this PR. First, the optProb name is directly passed in without casting it to a numpy character array, as f2py will automatically truncate or add the correct amount of padding. Second, the entries in `cw` that correspond to the names for the objective/RHS etc are set to the value of `cdummy` as found in SNOPT, so that internally in SNOPT they are replaced by a placeholder, in this case eight dashes.
What types of change …
> fixes strings in print out, in mProb,mObj,mRHS,mRng,mBnd

- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pySLSQP/pySLSQP.py
- pyoptsparse/pySNOPT/pySNOPT.py
… incorrect
This PR does the following:
* renamed `pi` to `lambdaStar` for the Lagrange multipliers
* removed saving the unscaled multipliers `pi` separately in `pySNOPT`
* removed saving the unscaled multipliers `pi` for SLSQP since they are not correct. We currently do not save any multiplier info for SLSQP
* changed the final print-out of the solution object to be more clear about multipliers
> Cleaned up code for Lagrange multipliers

- doc/install.rst
- pyoptsparse/pyOpt_optimization.py
Previously `six` was an optional dependency, but the code actually had it as a required dependency -- it will throw an error in some cases if `six` was not installed. See #61 for the issue.
This fix addresses the bug by explicitly requiring `six`. In the future, we may drop the dependency as we move to support only Python 3.
Running the tests as explained in #61 without `six` installed should now raise an error, with instructions to install it.
> Fix for requiring the six package

- pyoptsparse/__init__.py
- setup.py
This PR adds __version__ to the main module so that other packages can check the version of the installed pyoptsparse by querying "pyoptsparse.__version__".  (PEP 396 defines this standard.)
- Other (please describe)
This is a fix that further supports pyoptsparse usage as a python package. Adding __version__ allows the version to be queried automatically.  I also updated the version number in setup.py.
Note: These changes make a properly versioned release, so the current 1.1.0 release should be replaced with this commit. You could also choose to increment the release, maybe 1.1.1, but you will have to update the version number in both places.
Explain the steps needed to test the new code to verify that it …
> Added version number to the module

- pyoptsparse/pyParOpt/ParOpt.py
ParOpt requires mpi4py. However, we do not want this to be a requirement for those who do not need ParOpt. Therefore, the import statement has been moved to a try block so that it's not needed if you don't run ParOpt.
> mpi4py import

- .travis.yml
Links to coveralls.io has been added. There's a corresponding environment variable called COVERALLS_REPO_TOKEN which tells coveralls where to push the coverage info.
Perhaps we can talk about which folder/files we would like to omit, and maybe configure the .coveragerc file similar to how openMDAO handles it?
Also please squash this PR.
> Add coveralls

- doc/api/history.rst
- pyoptsparse/__init__.py
- pyoptsparse/pyOpt_optimizer.py
If the package has been installed in the default `site-packages` folder, then git is not able to find the git commit hash since it is not the source code folder where git lives. The git hash is then empty in most cases, which is not very useful. More worryingly, this seem to trigger some PETSc segfaults in some cases -- we haven't fully debugged this yet, as the behavior seems to be nondeterministic. However, to be safe, we have decided to remove this feature. We aim to increment the package version more frequently in the future to provide a more meaningful way of keeping track of code versions.
> Removed storing git hash in history file

- pyoptsparse/pyOpt_optimizer.py
- test/test_hs015.py
There was a bug in release v2.0.1 involving hotstarts. Due to the way the hotstart is implemented, the history file is created elsewhere and various keys are copied over. The newly-added `metadata` key was not added, and therefore at the end of the optimization the `self.metadata` key cannot be found. This is now fixed.
To be clear, the issue affected cases with *both* `hotStart` and `storeHistory` enabled.
> Bugfix for hotstart when also saving history file

- pyoptsparse/pyOpt_optimizer.py
- test/test_hs071.py
Previously the values stored in the solution object was not scaled back. When scaling is applied, the final solution values change. This PR ensures that the objective, DV, and Lagrange multiplier values stay the same when objective, constraints and DVs are arbitrarily scaled.
Note: the `sol.fStar` field is broken (same as before). I did not have time to debug the issue.
See the newly-added test `test_snopt_scaling`.
> Fixing optimization scaling in solution object

- doc/conf.py
- doc/optimizers/pyalpso.rst
Minor fixes for the documentation to work with readthedocs:
* added the parent folder of `docs` to the `sys.path`, so autodoc can find the modules
* removed current theme, may want to delete the directory in the future, i.e. not ship custom themes with the package
> readthedocs update

- pyoptsparse/pyOpt_history.py
- test/test_hs015.py
- test/test_hs071.py
- test/test_large_sparse.py
- test/test_nsga2_multi_objective.py
- test/test_snopt_bugfix.py
- test/test_tp109.py
There was a bug in `getValues()` that caused the numpy arrays returned to be inconsistent in shape. This PR removes the messy logic, and simply uses `numpy.stack` to make sure the shapes are consistent. 
This PR also refactored some of the other tests. `assert_almost_equal` from numpy is also used instead of `self.assertAlmostEqual` in Python.
This issue came up with `names=Hessian`, which is a matrix. When stacked along multiple callCounters, the previous logic fails to return a 3-D array with the correct shape. I have now added tests in `test_hs015.py` to check this.
> Fix for inconsistent shape in return from getValues

- pyoptsparse/pyIPOPT/pyIPOPT.py
- test/test_hs071.py
The current version of pyIPOPT.py was not returning the return code from IPOPT.
The file has been updated to handle the return codes as given in https://github.com/coin-or/Ipopt/blob/master/src/Interfaces/IpReturnCodes_inc.h
Resolves: #90 
This is a fix for master but the same changes apply to v1.2 (for those people without the latest SNOPT).  They are available on branch ipopt_informs_v1_2 on my fork. (I don't seem to be able to submit a PR against a fork).
I have tested this fix locally on my system and it works as expected.  I have added tests of the inform value to IPOPT tests in the code.  All that is …
> Ipopt informs

- test/test_hs015.py
- test/test_hs071.py
- test/test_large_sparse.py
- test/test_optProb.py
- test/test_snopt_bugfix.py
- test/test_snopt_user_termination.py
By default, each optimizer has a default output file name.
I updated the tests to specify a unique filename for each test. That way, when tests are run concurrently with `testflo`, there are no file IO clashes.
> Specified output filenames for each test

- pyoptsparse/pyOpt_history.py
- pyoptsparse/pyOpt_optimizer.py
`getValues` tries to loop over all the `conNames`, which contains all the linear constraints too. So, when constructing the dictionary of values, it then tries to read those linear constraint values from `funcs`, which are of course not stored there. So I've modified it to just only read from `funcs` if the constraint is nonlinear.
> Fixed bug where getValues() tries to retrieve linear constraint values

- pyoptsparse/pyALPSO/alpso_ext.py
- pyoptsparse/pyNLPQLP/pyNLPQLP.py
- pyoptsparse/pyNOMAD/pyNOMAD.py
- pyoptsparse/pyOpt_constraint.py
- pyoptsparse/pyOpt_history.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pyOpt_variable.py
- pyoptsparse/pySNOPT/pySNOPT.py
- setup.py
This is a minor formatting fix. Due to the way things were coded before, long error messages were concatenated by just a series of strings. When I reformatted with black, it combined certain lines which were not long enough into a single line, resulting in these extra quotes. I removed them in this PR.
- Code style update (formatting, renaming)
> Minor format fix

- pyoptsparse/pyOpt_optimization.py
- test/test_optProb.py
This PR addresses the bug in #107 by changing setDVs to allow only a subset of DVs to be set. The full set of DVs is still used in the scaling to avoid errors in the mapping functions.
Closes #107 
Run test_optProb.py which has the new test "test_setDV_VarGroup"
> fixed setDVs bug when setting a subset of DVs

- README.md
- doc/optimizers/pyparopt.rst
We have decided to temporarily remove support for ParOpt, meaning we will no longer build ParOpt in our Docker images, and run pyParOpt tests within pyOptSparse.
This PR updates the documentation to reflect that change.
> Removing support for paropt

- README.md
- doc/guide.rst
- doc/install.rst
I removed outdated information in the installation instructions, both the `setup.py` approach for installation, as well as information on Windows install, since we do not currently support that.
I am also doing this partly to trigger a PR build for readthedocs, and testing that feature. 
> Updated installation instructions

- doc/conf.py
- doc/install.rst
- pyoptsparse/pyOpt_MPI.py
- pyoptsparse/pyParOpt/ParOpt.py
- test/test_require_mpi_env_var.py
This PR fixes issue #117.
The goal is to give the user some control over using mpi4py. The user can either say they don't want to run in parallel or explicitly say they must run in parallel. Otherwise, pyoptsparse currently tries to run in parallel as needed but if a suitable mpi4py is not available, there is a fallback to run in serial.
One test is to set `PYOPTSPARSE_REQUIRE_MPI` to '0'. Any tests that use ParOpt should fail since ParOpt needs to run in parallel and the environment variable is telling pyoptsparse to run in serial. 
> Added control over using mpi4py by setting environment variable PYOPTSPARSE_REQUIRE_MPI

- pyoptsparse/pyOpt_MPI.py
- pyoptsparse/pyParOpt/ParOpt.py
- test/test_require_mpi_env_var.py
We discovered some issues after merging #118:
- If we specify `PYOPTSPARSE_REQUIRE_MPI` but ParOpt does not exist, then an `ImportError` is raised
- If `mpi4py` does not exist, then some tests fail (but they are expected to fail since it specifies that we must use `mpi4py`)
I have updated the logic to check both imports, as well as which tests should pass/fail depending on if `mpi4py` exists.
I also updated formatting of one long string used to warn users when `mpi4py` does not exist.
> Bugfix for mpi4py import

- doc/install.rst
I updated the installation instructions, specifically for when SWIG is unavailable and the user does not require NSGA2.
> Update installation instructions for skipping NSGA2

- pyoptsparse/pyOpt_history.py
- test/test_tp109.py
This PR fixes two more bugs with the linear constraints:
- casting the constraint dict_keys into a list, so that the dictionary does not mutate during the loop if an item is removed. This bug was not caught by the test since the linear constraint was always the last constraint in the way the test was set up, and therefore was unaffected
- Simplified the way `conNames` was computed, somehow the previous implementation did not work as expected
I also added a test to `getValues` that tests the scale option.
> Additional linear constraint fixes

- pyoptsparse/pyIPOPT/setup.py
Fix an installation issue for the IPOPT solver. This specifically addresses the case when `$IPOPT_DIR` is set to `pyoptsparse/pyoptsparse/pyIPOPT/IPOPT`. The issue is #152 .
> fixed the IPOPT installation bug

- examples/snopt_bugfix.py
- pyoptsparse/postprocessing/OptView_baseclass.py
- pyoptsparse/postprocessing/OptView_dash.py
- pyoptsparse/pyCONMIN/pyCONMIN.py
- pyoptsparse/pyIPOPT/pyIPOPT.py
- pyoptsparse/pyNSGA2/pyNSGA2.py
- pyoptsparse/pyOpt_constraint.py
- pyoptsparse/pyOpt_gradient.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pyOpt_utils.py
- pyoptsparse/pyPSQP/pyPSQP.py
- pyoptsparse/pyParOpt/ParOpt.py
- pyoptsparse/pySLSQP/pySLSQP.py
- pyoptsparse/pySNOPT/pySNOPT.py
- setup.py
- test/test_optProb.py
- test/test_snopt_bugfix.py
- test/test_snopt_user_termination.py
Black recently released a new (hopefully last) beta version after a year or so, which is why the tests failed on the master branch. Here I updated the code so that it conforms to black again. As far as I can tell, the main change relevant for us is the new capability to handle docstrings, which is what most of the diffs are about.
- Formatting
> Updated black formatting

- .github/workflows/main.yml
- .travis.yml
- README.md
- doc/install.rst
- pyoptsparse/pyOpt_optimization.py
- setup.py
This PR removes support for Python 2. Once this is merged, pyOptSparse will no longer work with Python 2.
The main change was just removing the `six` package and changing the syntax to use the native py3 iterators.
- Breaking change (non-backwards-compatible fix or feature)
All existing tests pass on py3.
> Remove python 2 support

- pyoptsparse/pyOpt_history.py
- test/test_hs015.py
Currently, the `getValues` method in the `pyOpt_history` class only returns the histories of functions that are used as objectives or constraints. However, sometimes there are other functions of interest not used as either that user may want to track the history of anyway. This fix allows this by adding all the functions in the `'funcs'` dict to the list of those that can be returned by `getValues`.
You may want to make some changes to this, I'm not sure if including everything from `self.db["0"]["funcs"]` automatically includes all constraints and objectives or not. Are there also tests that would be affected by this change?
Explain the steps needed to test the new code to verify that it does indeed …
> Include non-objective/constraint functions in history output

- doc/optimizers/pysnopt.rst
- pyoptsparse/__init__.py
- pyoptsparse/pyIPOPT/pyIPOPT.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pySNOPT/pySNOPT.py
This PR extends support for SNOPT v7.7.5, which has the `snLog` call signatures restored so there was no need to modify the f2py interface. Changes are:
- Added `Backoff factor` option to control the backtracking factor during line search when encountering failed function evaluations
- Added `Proximal iterations limit` option for controlling the number of iterations in solving the proximal point problem
- The default value for this option has been changed from 200 to 10000 to ensure we solve the problem to optimality. This was also the default behaviour in the older SNOPT v7.2
Note that since the `Backoff factor` did not exist in v7.7.1, attempting to set it via `optOptions` will result in SNOPT saying 
```
XXX  Keyword not recognized:         BACKOFF
```
however, this is simply a warning …
> Update for SNOPT v7.7.5

- doc/ext/optimizertable.py
- doc/optimizers/pysnopt.rst
I updated the documentation to explain how SNOPT default options come from the optimizer and are not set by pySNOPT.
I have hidden the default values for SNOPT by modifying the Sphinx extension.
I also checked that other optimizers are using the default values, and that the documentation is consistent with the code.
Closes #135.
> Added option to hide default values in docs

- pyoptsparse/pySLSQP/pySLSQP.py
Closes https://github.com/mdolab/MACH-Aero/issues/31. 
File id 6 is often associated with `stdout` and as such was redirecting the adflow output to this file.
Run the tutorial as described in https://github.com/mdolab/MACH-Aero/issues/31.
> Changing the SLSQP output file id

- doc/api/history.rst
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pySNOPT/pySNOPT.py
- pyoptsparse/pySNOPT/source/f2py/snopt.pyf
- test/test_hs015.py
I added another key to `metadata` called `optVersion`, currently defaulting to `None`. I then wrapped the `snTitle` subroutine to extract the version information from SNOPT, and set it inside Python. This allows the history file to store the SNOPT version information which is useful for reproducibility of results.
Note that docs build will probably fail. I will update the way the options tables are generated and fix this.
I added a new test.
> Extract and store SNOPT version in history file

- doc/advancedFeatures.rst
- doc/index.rst
- doc/optimizers/SNOPT.rst
- pyoptsparse/__init__.py
- pyoptsparse/pyALPSO/pyALPSO.py
- pyoptsparse/pyCONMIN/pyCONMIN.py
- pyoptsparse/pyIPOPT/pyIPOPT.py
- pyoptsparse/pyNLPQLP/pyNLPQLP.py
- pyoptsparse/pyNOMAD/pyNOMAD.py
- pyoptsparse/pyNSGA2/pyNSGA2.py
- pyoptsparse/pyOpt_MPI.py
- pyoptsparse/pyOpt_history.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pyPSQP/pyPSQP.py
- pyoptsparse/pyParOpt/ParOpt.py
- pyoptsparse/pySLSQP/pySLSQP.py
- pyoptsparse/pySNOPT/pySNOPT.py
- test/test_hs015.py
- test/test_rosenbrock.py
This PR addresses several issues with hotstart
- closes #208
- closes #209
In this process, we've had to make the following changes:
- move `setHistory` to outside of the comm split for all optimizers. This allows us to set the initial DVs into the optProb before it's parsed to generate the numpy arrays for each optimizer
- wrap `setHistory` with MPI to ensure only a single proc is reading/writing to the history file
- updated `getValues` and the History class in general to allow accessing iterations which are not analysis. For some reason, certain optimizers (IPOPT in this case) will have the initial evaluation be a gradient one, I have no idea why. Since we only want the initial DVs this doesn't matter, but the code had to be updated to handle this.
Remaining TODOs:
What types of change …
> Fix several issues with hotstart

- pyoptsparse/pyOpt_optimization.py
This PR adds back the functions that were renamed in #221, as that technically broke backwards compatibility. We now throw a deprecation warning if the user tries to use those functions, and they will be removed in a future release.
N/A
> Add back the finalize functions but throw a deprecation warning

- pyoptsparse/pyOpt_gradient.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_optimizer.py
- test/test_tp109.py
When `objFun` is defined as a complex function to work with the complex-step derivative, there are two separate cases where complex values leak into the stored function values:
1) In the solution object. This was previously addressed in #102 but only for printing. I reverted this commit and changed `processObjtoVec` and `processContoVec` so that the stored value is real instead.
2) In the history file. I fixed this by casting `funcs` to real before they are cached.
Closes #76
> Made stored function values real

- pyoptsparse/pyOpt_optimization.py
- test/test_optProb.py
In #225, a bug was introduced whereby `self.nObj` was set to 0 in the init, and `finalize()` would increment this counter. However, multiple invocations of `finalize()` would not reset it to zero first, resulting in erroneous `nObj` values. This PR resets these counters so that `finalze()` is once again safe for multiple invocations. Note that this is only relevant if the user has changed `optProb` in between, since otherwise `finalize()` would be skipped altogether via the `self.finalized` flag check.
None, since we never tested against this use case.
> Fix counters bug

- doc/optimizers/IPOPT_options.yaml
- pyoptsparse/pyIPOPT/pyIPOPT.py
Removing the default pyIPOPT `print_level: 0` option and revert to IPOPT default (`print_level: 5`). 
This provides a more verbose and useful output on both the terminal and the `.out` file.
Verified locally by multiple users
> Revert IPOPT print level to optimizer default

- doc/optimizers/IPOPT_options.yaml
- pyoptsparse/pyIPOPT/pyIPOPT.py
- test/test_hs071.py
This reverts PR #233, and updates a few default IPOPT options:
- `print_level` is set to 0 again to suppress printing to screen
- `file_print_level` is set to 5 to print iterations to file (this is necessary because we set `print_level` to 0 and IPOPT automatically sets `file_print_level` to that)
- `print_user_options` is set to `yes` to always print a list of user-modified options
- `sb` set to `yes` to suppress printing of the IPOPT banner. Note that this is an undocumented option
- `option_file_name` has been removed since the default option is sufficient. This also gets rid of the annoying "Using option file "IPOPT_options.opt"` messages.
All tests pass, indicating that the options are being set …
> Update IPOPT default options

- pyoptsparse/pyOpt_optimization.py
Python by default does not show `DeprecationWarning` for most scenarios, so I switched warnings to use the default `UserWarning` which is by default shown.
> Changed DeprecationWarning to the default warning

- .github/test_real.sh
- doc/quickstart.rst
- pyoptsparse/pyOpt_objective.py
- pyoptsparse/pyOpt_optimization.py
The current Objective class has an `optimum` attribute that is never used or updated, but is printed on terminal when `optProb` or the final solution objects are printed. As this is misleading and unnecessary, I just removed it from the code.
Tested locally and the extra item does not appear anymore.
> Remove misleading `Optimum` key from terminal printout

- README.md
- doc/contribute.rst
- doc/guide.rst
- doc/install.rst
- doc/optimizers/IPOPT.rst
- doc/postprocessing.rst
- doc/quickstart.rst
I added information regarding conda, including installation instructions and a badge to the README. I also fixed some minor formatting issues in the RST files.
There are no code changes.
> Add conda to docs

- pyoptsparse/pyOpt_optimizer.py
While doing some profiling, I discovered that the deepcopy of the sensitivity dictionary during `_masterFunc2` is a rather slow operation. On my problem, an 11.5 second optimization was spending 1.95 seconds in that deepcopy. Removing it and replacing with just a reference dropped my runtime to 9.5 seconds.  Obviously this is peanuts if you are optimizing a problem with long objective and gradient compute times, but if you are performing many optimizations on small fast problems, that extra couple of seconds per run is important.
I think replacing with a reference is safe in most cases, if not all. The user-provided (or openmdao-provided) gradient function assembles that dictionary, and I can't think of any reasonable cases where something is going to change those values before the next …
> remove deepcopy of sensitivity dict to improve performance

- pyoptsparse/postprocessing/OptView.py
Choosing the save tec file button will not work for OptView.py. It returned a "dict_keys object is not subscriptable" error. Need to convert the dict_keys to a list.
Fixed a bug for the save_tec function in OptView
> Fixed  an issue for the save_tec func in OptView

- doc/optimizers/SNOPT_options.yaml
- pyoptsparse/pySNOPT/pySNOPT.py
I changed the default SNOPT options to suppress the minor print log
Try it locally, the minor printing log no longer appears.
> Suppress SNOPT minor print log

- pyoptsparse/pyOpt_optimizer.py
- tests/test_rosenbrock.py
If an optimization crashes in the middle of a gradient call, attempting to hot start the optimization will give the following error:
```
.../pyoptsparse/pyOpt_optimizer.py", line 454, in _masterFunc2
args = self.sens(xuser, self.cache["funcs"])
KeyError: 'funcs'
```
I fixed this by re-evaluating the functions if the `funcs` key does not exist.
Regular urgency; one week
I tried to create a test, but this bug proved difficult to reproduce even with manual modification of the history file.
> Fixed hot start gradient bug

- doc/optimizers/SNOPT_options.yaml
- pyoptsparse/pySNOPT/pySNOPT.py
Closes #288. I chose not to set Hessian memory stuff since I think it's a bit confusing, and I didn't set the superbasics limit since I think that's a bit problem dependent. In any case, I'm happy to continue the discussion here if anyone feels strongly about adding any other default options here.
As long as it takes for us to converge to a reasonable set of options.
None, existing tests should cover it.
> Updated default pySNOPT options

- pyoptsparse/pyIPOPT/pyIPOPT.py
- setup.py
- tests/test_user_termination.py
The intent of this change is to enable the IPOPT Optimizer to respond to a user requested termination in the same way that the SNOPT Optimizer does.
As with SNOPT, a value of 2 returned in the `fail` flag from a user evaluation function will be interpreted as a request to terminate the optimization.  This is accomplished by means of the `intermediate_callback` in the IPOPT API.
Not urgent.
The existing `user_termination` test for SNOPT has been updated to test IPOPT as well.
- I ran `black` and `flake8` but left a few existing lines that `flake8` complained were over 80 columns
- my `black` made some changes that your `black` didn't like
> Enable user requested termination if IPOPT

- .github/environment.yml
#305 exposed an issue with using the latest Meson to build Windows. Turns out, the conda-forge feedstock already hardcoded the Meson version to 0.61 which would explain why there haven't been issues with the conda-forge build.
To get the tests to pass, I hard coded the Meson version in the `.github/environment.yaml` file to 0.61. Apparently, an issue has been opened in the Meson repo [here](https://github.com/mesonbuild/meson/issues/10778) discussing the issue. Until this is fixed, it seems 0.61 is the way to go.
> Hard code meson version for Windows build so that tests pass

- pyoptsparse/pySNOPT/pySNOPT.py
This PR allows the user to add/modify/remove entries in the iterDict which is passed to the user. This offers a second way of adding information to the history file (the first being adding stuff into `funcs`).
A few days
> Allow user to write stuff into iterDict

- .isort.cfg
- doc/install.rst
- doc/optimizers/IPOPT.rst
The current docs have a note about building IPOPT for pyOptSparse with linear solvers other than mumps. Now that meson is used, this is outdated.
> Updated IPOPT build instructions for other linear solvers

- pyoptsparse/pyNSGA2/pyNSGA2.py
- pyoptsparse/pyOpt_optimizer.py
- tests/test_nsga2_multi_objective.py
- tests/test_snopt_bugfix.py
This PR fixes the `sol.fStar` value for NSGA2. Basically, the optimized f value was not being passed to `createSolution`.
2 days
An associated test is added which fails without the fix.
> Fix `sol.fStar` for NSGA2

- doc/advancedFeatures.rst
- examples/tp109.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pySNOPT/pySNOPT.py
- tests/test_hs071.py
- tests/test_tp109.py
I updated the `informs` dictionary to include all the supported `INFO` exit codes in SNOPT 7.7 (see list on the [manual](http://www.sbsi-sol-optimize.com/manuals/SNOPT%20Manual.pdf), page 42).
A few of the current codes are not used in v7.7 anymore, so I removed them from the list. This will not affect backward compatibility as we don't support versions <7.7.
Closes #332 
P.S. I edited a few docstrings that were creating issues with the new flake8 rst checks, since this is the first PR affected by the new check for this repo
1-2 days
> Update informs list to be consistent with SNOPT 7.7 + updating docstrings for flake8 rst checks

- tests/test_hs071.py
- tests/test_tp109.py
The HS071 case runs too quickly to reliably test the SNOPT time limit option. I moved the test to the TP109 instead and decreased the time.
ASAP because the buildbot is failing
> Moved SNOPT time limit test to larger problem

- pyoptsparse/pyALPSO/alpso.py
- pyoptsparse/pyALPSO/alpso_ext.py
This is a simple fix for several occurrences of a deprecation in `alpso.py`:
```
swryan@Chimaera:~/dev/pyoptsparse/tests$ python test_sphere.py
/home/swryan/miniconda3/envs/dymos/lib/python3.11/site-packages/pyoptsparse/pyALPSO/alpso.py:58: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
if x0 != []:
/home/swryan/miniconda3/envs/dymos/lib/python3.11/site-packages/pyoptsparse/pyALPSO/alpso.py:113: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
if x0 != []:
/home/swryan/miniconda3/envs/dymos/lib/python3.11/site-packages/pyoptsparse/pyALPSO/alpso.py:178: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
if x0 != []:
```
Information about the deprecation is here: …
> fix deprecation in alpso

- tests/test_hs015.py
This PR reduces the tolerance on one failing test (hs015, SLSQP) to allow the ARM based Mac Mini to pass (see https://github.com/mdolab/docker/pull/170#issuecomment-1511253227 for more details).
No rush, but needed for https://github.com/mdolab/docker/pull/170
Run tests. Users with M1 or M2 CPUs should test this without and with the patch.
> Loosen tolerance on tests to support Mac ARM

- doc/contribute.rst
- doc/optimizers/SNOPT.rst
- pyoptsparse/pySNOPT/pySNOPT.py
- tests/test_other.py
Addresses #337 
I am totally open to suggestions on the name of this environment variable. For now it is explicit as possible.
Quickly - due to small scope of change, not urgency.
> Add ability to specify search path for SNOPT import with env var

- tests/test_nsga2_multi_objective.py
- tests/testing_utils.py
This test has caused problems in the past and now it's caused one conda-forge build to fail. I think it's probably best to just remove this time, don't think it's adding much value anyways.
Not urgent.
> Remove flaky tests

- pyoptsparse/__init__.py
- pyoptsparse/pyOpt_MPI.py
- pyoptsparse/pyOpt_optimization.py
Two types of warnings are removed:
* warning on failing to import `mpi4py`, IMO this is a bit annoying for those that are not using the parallel features
* deprecation warnings for things that were removed 2+ years ago
We may want to make a release after this is merged, and clearly explain in the release notes that these deprecations are now removed.
Not urgent
> Remove some warnings

- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_optimizer.py
So, let's unpack the story of what's going on.
1. Originally we removed the `objFun` field when serializing optProb since it's a callable
2. When using multiprocessing, it is important to hold onto those references (see #264), so we keep them if possible (see #266)
3. We also added `optProb.sens` in #212, it is also a callable similar to `objFun` but did not receive the same treatment
Now, instead of just doing the same thing as before, I changed the approach of serialization. When we work with the `Optimization` object, we only get rid of the MPI communicator. When we need to serialize it for the History object, we then remove those fields so they are not serialized. This separation of Optimization vs. History is a little bit cleaner IMO.
No rush. Please test this with lab tools (SNOPT + …
> Remove callables from optProb only when serializing in History file

- doc/optimizers/SNOPT_options.yaml
- pyoptsparse/pySNOPT/pySNOPT.py
- tests/test_hs015.py
- tests/test_other.py
- tests/test_rosenbrock.py
I updated the `snSTOP` function to save more variables by default in the Python layer. The option `Save major iteration variables` now defaults to an empty list. The following variables are saved (the user cannot turn these off)
- `isMajor`
- `nMajor`
- `nMinor`
- `step`
- `feasibility`
- `optimality`
- `merit`
- `condZHZ`
- `penalty`
and the following can be added via the option
- `Hessian`
- `slack`
- `lambda`
- `condZHZ`
- `nS`
- `BSwap`
- `maxVi`
- `penalty_vector`
Happy to discuss names/which ones should be saved by default. I think it's possible to have everything in the major iteration log saved, but the defaults I feel are the ones people actually care about (at least given my limited knowledge of SNOPT).
A few days. Maybe we can do a minor release after this and #346 are both …
> Save more variables by default in SNOPT history file

- pyoptsparse/__init__.py
- pyoptsparse/pyOpt_constraint.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_utils.py
- pyoptsparse/types.py
It's possible to have an unsized numpy array, e.g.
```
>>> x = np.array(5)
>>> x.shape
()
```
In such cases, the `isscalar` check fails:
```
>>> np.isscalar(np.array(5))
False
```
In this PR, I refactored this code into a utility function `_broadcast_to_array`, and switched to using `numpy.broadcast_to` which should work for all value types. This simplifies the code somewhat. I have commented below on things that may require attention in the review process.
1-2 days.
I did not add any tests.
> More tolerant scalar check

- doc/install.rst
- doc/optimizers/IPOPT.rst
- doc/optimizers/SNOPT.rst
This PR adds installation instructions using OpenMDAO's `build_pyoptsparse` script on the installation documentation page.
This script has already been mentioned on the IPOPT page, but I think it's worth putting this on the installation page for more attention. (This script is probably the easiest way to install IPOPT and SNOPT, especially on macOS, but I recently realized that some people are not aware of it.)
a week
> Installation docs update

- doc/install.rst
- tests/test_nsga2_multi_objective.py
- tests/test_rosenbrock.py
- tests/testing_utils.py
Closes #345. Also updated docs slightly + added an nsga2 test to the Rosenbrock problem.
1 week
> Make nsga2 tests optional + docs update

- .github/test_real.sh
- pyoptsparse/postprocessing/OptView.py
- pyoptsparse/pyALPSO/pyALPSO.py
- pyoptsparse/pyIPOPT/pyIPOPT.py
- pyoptsparse/pySLSQP/pySLSQP.py
- pyoptsparse/pySNOPT/pySNOPT.py
- pyoptsparse/types.py
- tests/test_nsga2_multi_objective.py
Closes #361,
Closes #359.
Also updated the `testflo` flag since we now have IPOPT on Intel images.
1 week
> Remove deprecations

- pyoptsparse/pySNOPT/pySNOPT.py
- tests/testing_utils.py
> Fix test for earlier SNOPT versions

- .github/test_real.sh
- pyoptsparse/pyOpt_solution.py
Closes #368. In addition, added the `--disallow_deprecations` flag to avoid this happening again. For stable images to pass PR #370 needs to be merged first.
Once tests pass, and after PR #370
> Fix numpy 1.25 deprecation warnings

- pyoptsparse/__init__.py
- pyoptsparse/pyNSGA2/source/nsga2.h
Merge the patch from conda-forge/pyoptsparse-feedstock#36 upstream.
1 week
> NSGA2 patch

- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pyParOpt/ParOpt.py
call when jacType == "csr" so that it retuns CSR data instead of passing through
Minor bug fix
I checked it using ParOptSparse which requires the Jacobian matrix in a CSR structure
> fixed convertJacobian 

- tests/test_tp109.py
Our Mac runner is fast and sometimes does not run into the time limit for the SNOPT test where we want the optimization to time out. I decreased the time limit to hopefully address this.
2-3 days
The test still works on my workstation, but I didn't test this on the Mac runner.
> Decreased time limit for SNOPT informs test

- pyoptsparse/pySLSQP/source/slsqp.f
Output file formatting is inconsistent and missing characters in `ALGORITHM`
```
---------------------------------------------------------------------------
START OF THE SEQUENTIAL LEAST SQUARES PROGRAMMING ALGORIT  
---------------------------------------------------------------------------
PARAMETERS:
ACC =   0.1000D-05
MAXITER =500
IPRINT =   1
IOUT =  60
```
This PR adjusts the output and after it should look
```
---------------------------------------------------------------------------
START OF THE SEQUENTIAL LEAST SQUARES PROGRAMMING ALGORITHM
---------------------------------------------------------------------------
PARAMETERS:
ACC =   0.1000D-05
MAXITER = 500
IPRINT =   1
IOUT =  60
```
No rush
Run SLSQP optimization before and after the fix and compare outpu
> Fix formatting in SLSQP output file

- doc/optimizers/NLPQLP.rst
Update the docs to reflect we now test and support the latest version of NPLQLP, v5.0.3. 
Closes https://github.com/mdolab/pyoptsparse/issues/380
No rush
> Update supported versions in NLPQLP documentation

- pyoptsparse/pyParOpt/ParOpt.py
Closes #384 
Note that we are not currently testing any version other than v2.0.2, but the changes here should be backwards compatible (assuming tests pass). This will be more meaningful once we have the newer version up and running, but in the mean time it should provide a stopgap solution.
A few days
> Update paropt interface

- pyoptsparse/pyALPSO/pyALPSO.py
- pyoptsparse/pyCONMIN/pyCONMIN.py
- pyoptsparse/pyIPOPT/pyIPOPT.py
- pyoptsparse/pyNLPQLP/pyNLPQLP.py
- pyoptsparse/pyNSGA2/pyNSGA2.py
- pyoptsparse/pyOpt_utils.py
- pyoptsparse/pyPSQP/pyPSQP.py
- pyoptsparse/pyParOpt/ParOpt.py
- pyoptsparse/pySLSQP/pySLSQP.py
- pyoptsparse/pySNOPT/pySNOPT.py
- tests/test_other.py
- tests/test_require_mpi_env_var.py
- tests/test_snopt_bugfix.py
- tests/test_user_termination.py
- tests/testing_utils.py
Closes #187 
Few days
No new tests, no new change in behaviour other than `ImportError` is now raised instead of generic `Error`.
> Better import error

- tests/test_user_termination.py
This is a small fix to the message raised when this test is skipped.  The test is parameterized and could be testing one of two optimizers (IPOPT or SNOPT), but the message is hard coded to SNOPT.
```
/home/runner/work/pyoptsparse/pyoptsparse/tests/test_user_termination.py:TestUserTerminationStatus.test_obj_0_IPOPT  ... SKIP (00:00:0.00, 145 MB)
Optimizer not available: IPOPT
/home/runner/work/pyoptsparse/pyoptsparse/tests/test_user_termination.py:TestUserTerminationStatus.test_obj_1_SNOPT ... OK (00:00:0.01, 145 MB)
/home/runner/work/pyoptsparse/pyoptsparse/tests/test_user_termination.py:TestUserTerminationStatus.test_sens_0_IPOPT  ... SKIP (00:00:0.00, 145 MB)
Optimizer not available: SNOPT
/home/runner/work/pyoptsparse/pyoptsparse/tests/test_user_termination.py:TestUserTerminationStatus …
```
> fix skip message

- pyoptsparse/__init__.py
- pyoptsparse/pyOpt_history.py
- tests/test_hs015.py
If the initial evaluation fails for SNOPT, exit 61 is returned. However, this results in an empty history file with `major=True`, which errors out:
```
File ".../pyoptsparse/pyOpt_history.py", line 654, in getValues
data[name] = np.stack(data[name], axis=0)
File ".../numpy/core/shape_base.py", line 445, in stack
raise ValueError('need at least one array to stack')
```
This PR fixes this issue.
2 days
> Fix empty hist

- pyoptsparse/pySNOPT/pySNOPT.py
The idea is that, 
1. we flush `stdout` and `stderr` before calling the optimizer, in case prints from the runscript are buffered
2. we flush the output files (which could also be streams) after the end of the optimization, so that stuff printed in the runscript after do not get mixed.
I know we can and should do this for all optimizers, I actually tried to refactor some stuff into "pre-optimization" and "post-optimization" functions shared across all optimizers. But, I stumbled across #402 which means I couldn't actually verify what I was doing with the `dummyConstraint` was not introducing bugs. We can come back to it after that stuff is all cleaned up.
> flush streams and files before/after optimization

- .github/environment.yml
- pyoptsparse/__init__.py
- pyoptsparse/pyIPOPT/pyIPOPT.py
- pyoptsparse/pyOpt_optimizer.py
- setup.py
- tests/test_optimizer.py
Some optimizers don't simultaneously call `_masterFunc` with the objective and constraint evaluation. In these cases, if the primal fails, the fail flag will only return the accurate value when the cache is not used (the case that actually calls the objective/constraint function). When the cache is used, the fail flag is always returned as `0`. A similar behavior occurs with the gradient evaluation. This PR caches the fail flag to fix this edge case.
Secondly, the pyIPOPT wrapper does not do anything if the `_masterFunc` returns a `True` fail flag (`1`). Even if any of the functions fail, IPOPT will just push on as if nothing happened. A CFD-based optimization case I saw with this was that it would get a mesh failure, immediately evaluate the gradients, go straight back to a mesh failure, …
> Fix `_masterFunc2` fail flag caching and add fail flag identification to IPOPT

- doc/guide.rst
- pyoptsparse/pyOpt_optimizer.py
- tests/test_lincon_error.py
- tests/test_snopt_bugfix.py
- tests/test_user_termination.py
pyOptSparse computes the linear constraints exclusively based on `jac`, `lower`, and `upper` entries of `addConGroup`, and it ignores the linear constraint value returned by the user-defined obj/con function. This is confusing and can result in unexpected behavior (see related #296).
This PR adds a linear constraint checkerto make sure that a user-defined obj/con function does **not** return linear constraint values. If it does, pyOptSparse will raise an error. I also updated the documentation accordingly.
I fixed a few existing tests that have been computing linear constraint values in the obj/con function (which we should not). I also added a test to check if pyOptSparse raises an error as expected.
This change will break some existing runscripts that return linear constraint values in …
> Added linear constraint check and updated documentation

- pyoptsparse/pySLSQP/pySLSQP.py
- pyoptsparse/pySLSQP/source/lsq.f
- tests/test_slsqp.py
One of the key differences between the pyOptSparse SLSQP implementation and the SciPy SLSQP implementation is strong bound enforcement. This was added the the SciPy implementation in these two PRs
https://github.com/scipy/scipy/pull/4502
https://github.com/scipy/scipy/pull/13009
These changes are fairly small and easy enough to port over. I've proposed this with this PR. This I suppose should fix #301 and relate to #303.
This is not overly pressing, but my team uses OpenMDAO with the SciPy SLSQP rather than the pyOptSparse driver due to bound enforcement issues, so this will allow us to shift over to pyOptSparse once merged.
I ran the hs015.py example and brought the initial guess outside to the bounds.
> Strongly enforce SLSQP Bounds

- pyoptsparse/pyIPOPT/pyIPOPT.py
- pyoptsparse/pyOpt_optimization.py
- pyoptsparse/pyOpt_solution.py
- tests/test_hs071.py
- tests/testing_utils.py
Added lagrange multipliers to IPOPT's output. Note that in the call to _createSolution we negate the multiplier values so that they are consistent with those returned by SNOPT. My understanding is that this is a matter of convention (due to the internal representations of the problems in the two optimizers).
The lagrange multipliers in the string representation of the solution are now correct.
Resolves #415 
This change is not urgent.
I've added a test to hs071 that verifies that the lagrange multipliers returned by SNOPT and IPOPT are correct.
> IPOPT now returns Lagrange multpliers using the same sign convention as SNOPT.

- .github/test_real.sh
- .github/windows.yaml
- .github/workflows/windows-build.yml
- pyoptsparse/pyOpt_optimizer.py
- pyoptsparse/pySNOPT/pySNOPT.py
- tests/test_hs015_parallel.py
Any script that runs in parallel check pass snSTOP handle and check if all mpi ranks call the function and have the same input arguments.
> parallel snstop

- .github/environment.yml
- .github/workflows/windows-build.yml
Fix the window build on the in-development numpy 2.0 branch.
There were a few problems:
1. `set FC=flang` is not necessary - this env var is set by activation scripts provided by the conda-forge `flang_impl_win-64` package. The correct compiler variable is `FC=flang-new` anyway.
2. Similarly, `set CC=` is not necessary, as it is set by the `vc` "activation" package from conda-forge. It looks like this variable was previously set to `clang`. On conda-forge we will most likely build with MSVC, so might as well just leave it as that for now.
3. We need to link with the LLVM linker `ld-lld`, not the MSVC linker `link`. The conda-forge clang/flang packages set the `LD` variable to `ld-lld`, but _Meson_ doesn't respect the `LD` variable. Therefore, we need to re-export these to variables that …
> Fix windows build for numpy 2.0

- .github/environment.yml
- .github/workflows/windows-build.yml
- setup.py
This PR improves the apparently flaky Windows build by making it better match the conda-forge build.
Flang is pinned to 5, which is the same as the current conda-forge global pin. The previous builds were using "latest" Flang, which resolved to 19. I'm not sure why the Flang 19 builds were flaky.
Note that conda-forge is currently migrating to Flang 19. As more conda-forge projects migrate to Flang 19, we can consider updating the CI here to Flang 19, leaning on the experience of the increasing number of conda-forge packages using Flang 19.
> Improve windows build 

- pyoptsparse/pyNSGA2/source/swig/nsga2.i
Discovered in conda-forge/pyoptsparse-feedstock#60, the same patch was applied there to successfully build py313.
A few days
None
> Update removed C API in py313

- .github/build_real.sh
- .github/workflows/linux-build.yml
- setup.py
Adds some basic GHA tests, because we do not currently test _optional_ optimizer installation in our docker tests and I want to make sure nothing breaks with 1) optional installation/dependency not breaking, and 2) tests get skipped properly. We should merge this one before #433 to make sure everything looks good with mesonpy.
> Add bare-bones GHA tests

- README.md
- doc/install.rst
- pyoptsparse/__init__.py
- pyoptsparse/pyNSGA2/meson.build
- pyoptsparse/pyNSGA2/pyNSGA2.py
- pyproject.toml
- tests/test_nsga2_multi_objective.py
- tests/testing_utils.py
SWIG used to be an optional dependency, but nowadays it is hosted on pyPI and relatively easy to include. Therefore, I propose that we make SWIG a required build dep and therefore NSGA2 an optimizer that is built by default. This will also hopefully simplify some issues people have regarding installation.
A few days, preferably after #434.
> Make swig mandatory and therefore NSGA2 a default optimizer

- pyoptsparse/__init__.py
- pyoptsparse/pyOpt_solution.py
- tests/test_other.py
Created from #450.
Realized that we effectively broke sol_inform in #437 because we were previously using a dict. This is now fixed by implementing `__getitem__`, and I think we should just make a patch release ASAP, this oversight is probably going to break pretty much everyone's code...
>  Fix SolutionInform dict access

- doc/advancedFeatures.rst
- doc/api/optimizer.rst
- doc/conf.py
- doc/guide.rst
- doc/quickstart.rst
- doc/requirements.txt
- pyoptsparse/pyOpt_optimizer.py
Add autolink to docs. I'll add some more type hints in the future.
> Add autolink

- doc/contribute.rst
Updated the coding style documentation page as we switched to Ruff. We now simply link to the Mach-Aero documentation page on code styling, as we use the same setup.
I also added `isort` documentation.
1 day
> Updated coding style documention
